instance_type       = "t3.micro"
ami                 = "ami-00ca32bbc84273381"
ingress_port        = "80"
ingress_protocol    = "tcp"
ingress_cidr_blocks = "x.x.x.x/32"
instance_role       = "jco_ec2-with-s3-role"
ec2_identifier      = "02"